include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - test/helpers/*.mocks.dart
    - lib/models/*.g.dart
  errors:
    unnecessary_string_interpolations: ignore
    prefer_typing_uninitialized_variables: ignore
    constant_identifier_names: ignore
    prefer_const_constructors: ignore
    overridden_fields: ignore
    avoid_function_literals_in_foreach_calls: ignore
    avoid_renaming_method_parameters: ignore
    todo: ignore