// Mocks generated by Mockito 5.0.15 from annotations
// in hng/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i2;
import 'dart:io' as _i21;
import 'dart:ui' as _i12;

import 'package:dio/dio.dart' as _i3;
import 'package:flutter/material.dart' as _i9;
import 'package:hng/models/api_response.dart' as _i19;
import 'package:hng/models/channel_members.dart' as _i16;
import 'package:hng/models/channel_model.dart' as _i15;
import 'package:hng/models/channels_search_model.dart' as _i24;
import 'package:hng/models/organization_model.dart' as _i6;
import 'package:hng/models/user_search_model.dart' as _i20;
import 'package:hng/package/base/jump_to_request/jump_to_api.dart' as _i23;
import 'package:hng/package/base/server-request/api/zuri_api.dart' as _i18;
import 'package:hng/package/base/server-request/channels/channels_api_service.dart'
    as _i14;
import 'package:hng/package/base/server-request/dms/dms_api_service.dart'
    as _i13;
import 'package:hng/services/centrifuge_service.dart' as _i17;
<<<<<<< HEAD
import 'package:hng/services/connectivity_service.dart' as _i22;
=======
import 'package:hng/services/connectivity_service.dart' as _i21;
>>>>>>> f756b28fe50f857b59b73fc2a3f7afb0540b4cf4
import 'package:hng/services/local_storage_services.dart' as _i7;
import 'package:hng/services/media_service.dart' as _i26;
import 'package:hng/services/user_service.dart' as _i5;
<<<<<<< HEAD
import 'package:hng/utilities/enums.dart' as _i23;
=======
import 'package:hng/utilities/enums.dart' as _i22;
>>>>>>> f756b28fe50f857b59b73fc2a3f7afb0540b4cf4
import 'package:hng/utilities/failures.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i8;
import 'package:stacked_themes/src/theme_manager.dart' as _i11;
import 'package:stacked_themes/src/theme_service.dart' as _i10;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeStreamController_0<T> extends _i1.Fake
    implements _i2.StreamController<T> {}

class _FakeDio_1 extends _i1.Fake implements _i3.Dio {}

class _FakeFailure_2 extends _i1.Fake implements _i4.Failure {}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i5.UserService {
  @override
  set organizationModel(_i6.OrganizationModel? _organizationModel) => super
      .noSuchMethod(Invocation.setter(#organizationModel, _organizationModel),
          returnValueForMissingStub: null);
  @override
  String get currentOrgId =>
      (super.noSuchMethod(Invocation.getter(#currentOrgId), returnValue: '')
          as String);
  @override
  String get currentOrgName =>
      (super.noSuchMethod(Invocation.getter(#currentOrgName), returnValue: '')
          as String);
  @override
  String get currentOrgUrl =>
      (super.noSuchMethod(Invocation.getter(#currentOrgUrl), returnValue: '')
          as String);
  @override
  String get authToken =>
      (super.noSuchMethod(Invocation.getter(#authToken), returnValue: '')
          as String);
  @override
  String get userId =>
      (super.noSuchMethod(Invocation.getter(#userId), returnValue: '')
          as String);
  @override
  String get userEmail =>
      (super.noSuchMethod(Invocation.getter(#userEmail), returnValue: '')
          as String);
  @override
  void setOrganization() =>
      super.noSuchMethod(Invocation.method(#setOrganization, []),
          returnValueForMissingStub: null);
  @override
  void setCurrentOrganizationId(String? currentOrgId) => super.noSuchMethod(
      Invocation.method(#setCurrentOrganizationId, [currentOrgId]),
      returnValueForMissingStub: null);
  @override
  void setUserAndToken(
          {String? authToken, String? userId, String? userEmail}) =>
      super.noSuchMethod(
          Invocation.method(#setUserAndToken, [],
              {#authToken: authToken, #userId: userId, #userEmail: userEmail}),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SharedPreferenceLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferenceLocalStorage extends _i1.Mock
    implements _i7.SharedPreferenceLocalStorage {
  @override
  _i2.Future<dynamic> setBool(String? key, bool? value) =>
      (super.noSuchMethod(Invocation.method(#setBool, [key, value]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> setString(String? key, String? value) =>
      (super.noSuchMethod(Invocation.method(#setString, [key, value]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> setDouble(String? key, num? value) =>
      (super.noSuchMethod(Invocation.method(#setDouble, [key, value]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(Invocation.method(#setStringList, [key, value]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);
  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);
  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);
  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);
  @override
  _i2.Future<bool?> clearData(String? key) =>
      (super.noSuchMethod(Invocation.method(#clearData, [key]),
          returnValue: Future<bool?>.value()) as _i2.Future<bool?>);
  @override
  _i2.Future<bool?> clearStorage() =>
      (super.noSuchMethod(Invocation.method(#clearStorage, []),
          returnValue: Future<bool?>.value()) as _i2.Future<bool?>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i8.NavigationService {
  @override
  String get previousRoute =>
      (super.noSuchMethod(Invocation.getter(#previousRoute), returnValue: '')
          as String);
  @override
  String get currentRoute =>
      (super.noSuchMethod(Invocation.getter(#currentRoute), returnValue: '')
          as String);
  @override
  _i9.GlobalKey<_i9.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(Invocation.method(#nestedNavigationKey, [index]))
          as _i9.GlobalKey<_i9.NavigatorState>?);
  @override
  void config(
          {bool? enableLog,
          bool? defaultPopGesture,
          bool? defaultOpaqueRoute,
          Duration? defaultDurationTransition,
          bool? defaultGlobalState,
          String? defaultTransition}) =>
      super.noSuchMethod(
          Invocation.method(#config, [], {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransition: defaultTransition
          }),
          returnValueForMissingStub: null);
  @override
  _i2.Future<T?>? navigateWithTransition<T>(_i9.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i9.Curve? curve,
          _i8.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i8.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#navigateWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? replaceWithTransition<T>(_i9.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i9.Curve? curve,
          _i8.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i8.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#replaceWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i2.Future<T?>?);
  @override
  bool back<T>({T? result, int? id}) => (super.noSuchMethod(
      Invocation.method(#back, [], {#result: result, #id: id}),
      returnValue: false) as bool);
  @override
  void popUntil(_i9.RoutePredicate? predicate) =>
      super.noSuchMethod(Invocation.method(#popUntil, [predicate]),
          returnValueForMissingStub: null);
  @override
  void popRepeated(int? popTimes) =>
      super.noSuchMethod(Invocation.method(#popRepeated, [popTimes]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<T?>? navigateTo<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#navigateTo, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? navigateToView<T>(_i9.Widget? view,
          {dynamic arguments,
          int? id,
          bool? opaque,
          _i9.Curve? curve,
          _i8.Bindings? binding,
          Duration? duration,
          bool? fullscreenDialog = false,
          bool? popGesture,
          bool? preventDuplicates = true,
          _i8.Transition? transition}) =>
      (super.noSuchMethod(Invocation.method(#navigateToView, [
        view
      ], {
        #arguments: arguments,
        #id: id,
        #opaque: opaque,
        #curve: curve,
        #binding: binding,
        #duration: duration,
        #fullscreenDialog: fullscreenDialog,
        #popGesture: popGesture,
        #preventDuplicates: preventDuplicates,
        #transition: transition
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? replaceWith<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#replaceWith, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? clearStackAndShow<T>(String? routeName,
          {dynamic arguments, int? id, Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearStackAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #parameters: parameters
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? clearTillFirstAndShow<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? clearTillFirstAndShowView<T>(_i9.Widget? view,
          {dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShowView, [view],
          {#arguments: arguments, #id: id})) as _i2.Future<T?>?);
  @override
  _i2.Future<T?>? pushNamedAndRemoveUntil<T>(String? routeName,
          {_i9.RoutePredicate? predicate, dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#pushNamedAndRemoveUntil, [
        routeName
      ], {
        #predicate: predicate,
        #arguments: arguments,
        #id: id
      })) as _i2.Future<T?>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SnackbarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnackbarService extends _i1.Mock implements _i8.SnackbarService {
  @override
  void registerSnackbarConfig(_i8.SnackbarConfig? config) =>
      super.noSuchMethod(Invocation.method(#registerSnackbarConfig, [config]),
          returnValueForMissingStub: null);
  @override
  void registerCustomSnackbarconfig(
          {dynamic customData, _i8.SnackbarConfig? config}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomSnackbarconfig, [],
              {#customData: customData, #config: config}),
          returnValueForMissingStub: null);
  @override
  void registerCustomMainButtonBuilder(
          {dynamic variant,
          _i9.Widget Function(String?, Function?)? builder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomMainButtonBuilder, [],
              {#variant: variant, #builder: builder}),
          returnValueForMissingStub: null);
  @override
  void registerCustomSnackbarConfig(
          {dynamic variant,
          _i8.SnackbarConfig? config,
          _i8.SnackbarConfig Function()? configBuilder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomSnackbarConfig, [], {
            #variant: variant,
            #config: config,
            #configBuilder: configBuilder
          }),
          returnValueForMissingStub: null);
  @override
  void showSnackbar(
          {String? title = r'',
          String? message,
          dynamic Function(dynamic)? onTap,
          Duration? duration = const Duration(seconds: 3),
          String? mainButtonTitle,
          void Function()? onMainButtonTapped}) =>
      super.noSuchMethod(
          Invocation.method(#showSnackbar, [], {
            #title: title,
            #message: message,
            #onTap: onTap,
            #duration: duration,
            #mainButtonTitle: mainButtonTitle,
            #onMainButtonTapped: onMainButtonTapped
          }),
          returnValueForMissingStub: null);
  @override
  _i2.Future<dynamic>? showCustomSnackBar(
          {String? message,
          dynamic customData,
          dynamic variant,
          String? title,
          String? mainButtonTitle,
          void Function()? onMainButtonTapped,
          Function? onTap,
          Duration? duration = const Duration(seconds: 1)}) =>
      (super.noSuchMethod(Invocation.method(#showCustomSnackBar, [], {
        #message: message,
        #customData: customData,
        #variant: variant,
        #title: title,
        #mainButtonTitle: mainButtonTitle,
        #onMainButtonTapped: onMainButtonTapped,
        #onTap: onTap,
        #duration: duration
      })) as _i2.Future<dynamic>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ThemeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeService extends _i1.Mock implements _i10.ThemeService {
  @override
  int get themeCount =>
      (super.noSuchMethod(Invocation.getter(#themeCount), returnValue: 0)
          as int);
  @override
  bool get isDarkMode =>
      (super.noSuchMethod(Invocation.getter(#isDarkMode), returnValue: false)
          as bool);
  @override
  _i10.ThemeManagerMode get selectedThemeMode =>
      (super.noSuchMethod(Invocation.getter(#selectedThemeMode),
          returnValue: _i10.ThemeManagerMode.light) as _i10.ThemeManagerMode);
  @override
  void setThemeManager(_i11.ThemeManager? manager) =>
      super.noSuchMethod(Invocation.method(#setThemeManager, [manager]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<dynamic> selectThemeAtIndex(int? themeIndex) =>
      (super.noSuchMethod(Invocation.method(#selectThemeAtIndex, [themeIndex]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  void toggleDarkLightTheme() =>
      super.noSuchMethod(Invocation.method(#toggleDarkLightTheme, []),
          returnValueForMissingStub: null);
  @override
  void setThemeMode(_i10.ThemeManagerMode? themeManagerMode) =>
      super.noSuchMethod(Invocation.method(#setThemeMode, [themeManagerMode]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i8.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i8.DialogBuilder>? builders) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomDialogBuilders, [builders]),
          returnValueForMissingStub: null);
  @override
  void registerCustomDialogBuilder(
          {dynamic variant,
          _i9.Widget Function(_i9.BuildContext, _i8.DialogRequest<dynamic>,
                  dynamic Function(_i8.DialogResponse<dynamic>))?
              builder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomDialogBuilder, [],
              {#variant: variant, #builder: builder}),
          returnValueForMissingStub: null);
  @override
  _i2.Future<_i8.DialogResponse<dynamic>?> showDialog(
          {String? title,
          String? description,
          String? cancelTitle,
          _i12.Color? cancelTitleColor,
          String? buttonTitle = r'Ok',
          _i12.Color? buttonTitleColor,
          bool? barrierDismissible = false,
          _i8.DialogPlatform? dialogPlatform}) =>
      (super.noSuchMethod(
              Invocation.method(#showDialog, [], {
                #title: title,
                #description: description,
                #cancelTitle: cancelTitle,
                #cancelTitleColor: cancelTitleColor,
                #buttonTitle: buttonTitle,
                #buttonTitleColor: buttonTitleColor,
                #barrierDismissible: barrierDismissible,
                #dialogPlatform: dialogPlatform
              }),
              returnValue: Future<_i8.DialogResponse<dynamic>?>.value())
          as _i2.Future<_i8.DialogResponse<dynamic>?>);
  @override
  _i2.Future<_i8.DialogResponse<T>?> showCustomDialog<T, R>(
          {dynamic variant,
          String? title,
          String? description,
          bool? hasImage = false,
          String? imageUrl,
          bool? showIconInMainButton = false,
          String? mainButtonTitle,
          bool? showIconInSecondaryButton = false,
          String? secondaryButtonTitle,
          bool? showIconInAdditionalButton = false,
          String? additionalButtonTitle,
          bool? takesInput = false,
          _i12.Color? barrierColor = const _i12.Color(2315255808),
          bool? barrierDismissible = false,
          String? barrierLabel = r'',
          dynamic customData,
          R? data}) =>
      (super.noSuchMethod(
              Invocation.method(#showCustomDialog, [], {
                #variant: variant,
                #title: title,
                #description: description,
                #hasImage: hasImage,
                #imageUrl: imageUrl,
                #showIconInMainButton: showIconInMainButton,
                #mainButtonTitle: mainButtonTitle,
                #showIconInSecondaryButton: showIconInSecondaryButton,
                #secondaryButtonTitle: secondaryButtonTitle,
                #showIconInAdditionalButton: showIconInAdditionalButton,
                #additionalButtonTitle: additionalButtonTitle,
                #takesInput: takesInput,
                #barrierColor: barrierColor,
                #barrierDismissible: barrierDismissible,
                #barrierLabel: barrierLabel,
                #customData: customData,
                #data: data
              }),
              returnValue: Future<_i8.DialogResponse<T>?>.value())
          as _i2.Future<_i8.DialogResponse<T>?>);
  @override
  _i2.Future<_i8.DialogResponse<dynamic>?> showConfirmationDialog(
          {String? title,
          String? description,
          String? cancelTitle = r'Cancel',
          String? confirmationTitle = r'Ok',
          bool? barrierDismissible = false,
          _i8.DialogPlatform? dialogPlatform}) =>
      (super.noSuchMethod(
              Invocation.method(#showConfirmationDialog, [], {
                #title: title,
                #description: description,
                #cancelTitle: cancelTitle,
                #confirmationTitle: confirmationTitle,
                #barrierDismissible: barrierDismissible,
                #dialogPlatform: dialogPlatform
              }),
              returnValue: Future<_i8.DialogResponse<dynamic>?>.value())
          as _i2.Future<_i8.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i8.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(Invocation.method(#completeDialog, [response]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i8.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i8.SheetBuilder>? builders) =>
      super.noSuchMethod(Invocation.method(#setCustomSheetBuilders, [builders]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<_i8.SheetResponse<dynamic>?> showBottomSheet(
          {String? title,
          String? description,
          String? confirmButtonTitle = r'Ok',
          String? cancelButtonTitle,
          bool? enableDrag = true,
          bool? barrierDismissible = true,
          bool? isScrollControlled = false,
          Duration? exitBottomSheetDuration,
          Duration? enterBottomSheetDuration,
          bool? ignoreSafeArea}) =>
      (super.noSuchMethod(
              Invocation.method(#showBottomSheet, [], {
                #title: title,
                #description: description,
                #confirmButtonTitle: confirmButtonTitle,
                #cancelButtonTitle: cancelButtonTitle,
                #enableDrag: enableDrag,
                #barrierDismissible: barrierDismissible,
                #isScrollControlled: isScrollControlled,
                #exitBottomSheetDuration: exitBottomSheetDuration,
                #enterBottomSheetDuration: enterBottomSheetDuration,
                #ignoreSafeArea: ignoreSafeArea
              }),
              returnValue: Future<_i8.SheetResponse<dynamic>?>.value())
          as _i2.Future<_i8.SheetResponse<dynamic>?>);
  @override
  _i2.Future<_i8.SheetResponse<T>?> showCustomSheet<T, R>(
          {dynamic variant,
          String? title,
          String? description,
          bool? hasImage = false,
          String? imageUrl,
          bool? showIconInMainButton = false,
          String? mainButtonTitle,
          bool? showIconInSecondaryButton = false,
          String? secondaryButtonTitle,
          bool? showIconInAdditionalButton = false,
          String? additionalButtonTitle,
          bool? takesInput = false,
          _i12.Color? barrierColor = const _i12.Color(2315255808),
          bool? barrierDismissible = true,
          bool? isScrollControlled = false,
          String? barrierLabel = r'',
          dynamic customData,
          R? data,
          bool? enableDrag = true,
          Duration? exitBottomSheetDuration,
          Duration? enterBottomSheetDuration,
          bool? ignoreSafeArea}) =>
      (super.noSuchMethod(
              Invocation.method(#showCustomSheet, [], {
                #variant: variant,
                #title: title,
                #description: description,
                #hasImage: hasImage,
                #imageUrl: imageUrl,
                #showIconInMainButton: showIconInMainButton,
                #mainButtonTitle: mainButtonTitle,
                #showIconInSecondaryButton: showIconInSecondaryButton,
                #secondaryButtonTitle: secondaryButtonTitle,
                #showIconInAdditionalButton: showIconInAdditionalButton,
                #additionalButtonTitle: additionalButtonTitle,
                #takesInput: takesInput,
                #barrierColor: barrierColor,
                #barrierDismissible: barrierDismissible,
                #isScrollControlled: isScrollControlled,
                #barrierLabel: barrierLabel,
                #customData: customData,
                #data: data,
                #enableDrag: enableDrag,
                #exitBottomSheetDuration: exitBottomSheetDuration,
                #enterBottomSheetDuration: enterBottomSheetDuration,
                #ignoreSafeArea: ignoreSafeArea
              }),
              returnValue: Future<_i8.SheetResponse<T>?>.value())
          as _i2.Future<_i8.SheetResponse<T>?>);
  @override
  void completeSheet(_i8.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(Invocation.method(#completeSheet, [response]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DMApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDMApiService extends _i1.Mock implements _i13.DMApiService {
  @override
  _i2.Future<List<dynamic>> getActiveDms() =>
      (super.noSuchMethod(Invocation.method(#getActiveDms, []),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i2.Future<List<dynamic>>);
  @override
  _i2.Future<String?> getUser(dynamic ids) =>
      (super.noSuchMethod(Invocation.method(#getUser, [ids]),
          returnValue: Future<String?>.value()) as _i2.Future<String?>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ChannelsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelsApiService extends _i1.Mock
    implements _i14.ChannelsApiService {
  @override
  _i2.StreamController<String> get controller =>
      (super.noSuchMethod(Invocation.getter(#controller),
              returnValue: _FakeStreamController_0<String>())
          as _i2.StreamController<String>);
  @override
  set controller(_i2.StreamController<String>? _controller) =>
      super.noSuchMethod(Invocation.setter(#controller, _controller),
          returnValueForMissingStub: null);
  @override
  _i2.Future<List<dynamic>> getActiveDms() =>
      (super.noSuchMethod(Invocation.method(#getActiveDms, []),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i2.Future<List<dynamic>>);
  @override
  _i2.Future<String> getChannelSocketId(String? channelId) =>
      (super.noSuchMethod(Invocation.method(#getChannelSocketId, [channelId]),
          returnValue: Future<String>.value('')) as _i2.Future<String>);
  @override
  _i2.Future<Map<dynamic, dynamic>?> joinChannel(String? channelId) =>
      (super.noSuchMethod(Invocation.method(#joinChannel, [channelId]),
              returnValue: Future<Map<dynamic, dynamic>?>.value())
          as _i2.Future<Map<dynamic, dynamic>?>);
  @override
  _i2.Future<List<dynamic>> getChannelMessages(String? channelId) =>
      (super.noSuchMethod(Invocation.method(#getChannelMessages, [channelId]),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i2.Future<List<dynamic>>);
  @override
  _i2.Future<dynamic> sendChannelMessages(
          String? channelId, String? userId, String? message) =>
      (super.noSuchMethod(
          Invocation.method(#sendChannelMessages, [channelId, userId, message]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<List<_i15.ChannelModel>> fetchChannel() =>
      (super.noSuchMethod(Invocation.method(#fetchChannel, []),
              returnValue:
                  Future<List<_i15.ChannelModel>>.value(<_i15.ChannelModel>[]))
          as _i2.Future<List<_i15.ChannelModel>>);
  @override
  _i2.Future<bool> createChannels(
          {String? name, String? description, bool? private}) =>
      (super.noSuchMethod(
          Invocation.method(#createChannels, [],
              {#name: name, #description: description, #private: private}),
          returnValue: Future<bool>.value(false)) as _i2.Future<bool>);
  @override
  _i2.Future<bool> deleteChannel(String? orgId, String? channelId) =>
      (super.noSuchMethod(Invocation.method(#deleteChannel, [orgId, channelId]),
          returnValue: Future<bool>.value(false)) as _i2.Future<bool>);
  @override
  _i2.Future<List<_i16.ChannelMembermodel>?> getChannelMembers(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#getChannelMembers, [id]),
              returnValue: Future<List<_i16.ChannelMembermodel>?>.value())
          as _i2.Future<List<_i16.ChannelMembermodel>?>);
  @override
  _i2.Future<void>? dispose() => (super.noSuchMethod(
      Invocation.method(#dispose, []),
      returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CentrifugeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCentrifugeService extends _i1.Mock implements _i17.CentrifugeService {
  @override
  _i2.StreamController<dynamic> get messageStreamController =>
      (super.noSuchMethod(Invocation.getter(#messageStreamController),
              returnValue: _FakeStreamController_0<dynamic>())
          as _i2.StreamController<dynamic>);
  @override
  set messageStreamController(
          _i2.StreamController<dynamic>? _messageStreamController) =>
      super.noSuchMethod(
          Invocation.setter(#messageStreamController, _messageStreamController),
          returnValueForMissingStub: null);
  @override
  void disconnect() => super.noSuchMethod(Invocation.method(#disconnect, []),
      returnValueForMissingStub: null);
  @override
  _i2.Future<_i2.Stream<dynamic>?> subscribe(String? channelSocketId) =>
      (super.noSuchMethod(Invocation.method(#subscribe, [channelSocketId]),
              returnValue: Future<_i2.Stream<dynamic>?>.value())
          as _i2.Future<_i2.Stream<dynamic>?>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [ZuriApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockZuriApi extends _i1.Mock implements _i18.ZuriApi {
  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_1())
          as _i3.Dio);
  @override
  _i2.StreamController<String> get controller =>
      (super.noSuchMethod(Invocation.getter(#controller),
              returnValue: _FakeStreamController_0<String>())
          as _i2.StreamController<String>);
  @override
  set controller(_i2.StreamController<String>? _controller) =>
      super.noSuchMethod(Invocation.setter(#controller, _controller),
          returnValueForMissingStub: null);
  @override
  _i2.Future<dynamic> get(String? string,
          {Map<String, dynamic>? queryParameters, String? token}) =>
      (super.noSuchMethod(
          Invocation.method(#get, [string],
              {#queryParameters: queryParameters, #token: token}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> post(String? string,
          {Map<String, dynamic>? body, String? token}) =>
      (super.noSuchMethod(
          Invocation.method(#post, [string], {#body: body, #token: token}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> put(String? string,
          {Map<String, dynamic>? body, String? token}) =>
      (super.noSuchMethod(
          Invocation.method(#put, [string], {#body: body, #token: token}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<_i19.ApiResponse?> patch(String? path,
          {Map<String, dynamic>? body, String? token}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [path], {#body: body, #token: token}),
              returnValue: Future<_i19.ApiResponse?>.value())
          as _i2.Future<_i19.ApiResponse?>);
  @override
  _i2.Future<_i19.ApiResponse?> delete(String? string,
          {Map<String, dynamic>? body, String? token}) =>
      (super.noSuchMethod(
          Invocation.method(#delete, [string], {#body: body, #token: token}),
          returnValue:
              Future<_i19.ApiResponse?>.value()) as _i2
          .Future<_i19.ApiResponse?>);
  @override
  _i2.Future<dynamic> login({String? email, String? password, dynamic token}) =>
      (super.noSuchMethod(
          Invocation.method(
              #login, [], {#email: email, #password: password, #token: token}),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> signUp(
          {String? email,
          String? password,
          String? firstName,
          String? lastName,
          String? displayName,
          String? phoneNumber,
          String? token}) =>
      (super.noSuchMethod(
          Invocation.method(#signUp, [], {
            #email: email,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
            #displayName: displayName,
            #phoneNumber: phoneNumber,
            #token: token
          }),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<List<_i6.OrganizationModel>> fetchListOfOrganizations(
          dynamic token) =>
      (super.noSuchMethod(Invocation.method(#fetchListOfOrganizations, [token]),
              returnValue: Future<List<_i6.OrganizationModel>>.value(
                  <_i6.OrganizationModel>[]))
          as _i2.Future<List<_i6.OrganizationModel>>);
  @override
  _i2.Future<List<_i6.OrganizationModel>> getJoinedOrganizations(
          dynamic token, String? email) =>
      (super.noSuchMethod(
              Invocation.method(#getJoinedOrganizations, [token, email]),
              returnValue: Future<List<_i6.OrganizationModel>>.value(
                  <_i6.OrganizationModel>[]))
          as _i2.Future<List<_i6.OrganizationModel>>);
  @override
  _i2.Future<dynamic> fetchOrganizationInfo(String? id, dynamic token) => (super
      .noSuchMethod(Invocation.method(#fetchOrganizationInfo, [id, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> fetchOrganizationByUrl(String? url, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#fetchOrganizationByUrl, [url, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<bool> joinOrganization(
          String? orgId, String? email, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#joinOrganization, [orgId, email, token]),
          returnValue: Future<bool>.value(false)) as _i2.Future<bool>);
  @override
  _i2.Future<String> createOrganization(String? email, dynamic token) => (super
      .noSuchMethod(Invocation.method(#createOrganization, [email, token]),
          returnValue: Future<String>.value('')) as _i2.Future<String>);
  @override
  _i2.Future<dynamic> updateOrgUrl(String? orgId, String? url, dynamic token) =>
      (super.noSuchMethod(Invocation.method(#updateOrgUrl, [orgId, url, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> updateOrgName(
          String? orgId, String? name, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#updateOrgName, [orgId, name, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> updateOrgLogo(
          String? orgId, String? url, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#updateOrgLogo, [orgId, url, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> addMemberToOrganization(
          String? orgId, String? email, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#addMemberToOrganization, [orgId, email, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<List<_i20.UserSearch>> fetchMembersInOrganization(
          String? orgId, dynamic token) =>
      (super.noSuchMethod(
              Invocation.method(#fetchMembersInOrganization, [orgId, token]),
              returnValue:
                  Future<List<_i20.UserSearch>>.value(<_i20.UserSearch>[]))
          as _i2.Future<List<_i20.UserSearch>>);
  @override
  _i2.Future<dynamic> getChannelSocketId(
          String? channelId, String? orgId, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#getChannelSocketId, [channelId, orgId, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<List<dynamic>> getActiveRooms(
          String? orgId, String? userId, dynamic token) =>
      (super.noSuchMethod(
              Invocation.method(#getActiveRooms, [orgId, userId, token]),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i2.Future<List<dynamic>>);
  @override
  _i2.Future<List<dynamic>> getActiveDms(String? orgId, dynamic token) =>
      (super.noSuchMethod(Invocation.method(#getActiveDms, [orgId, token]),
              returnValue: Future<List<dynamic>>.value(<dynamic>[]))
          as _i2.Future<List<dynamic>>);
  @override
  _i2.Future<Map<dynamic, dynamic>> joinChannel(
          String? channelId, String? userId, String? orgId, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#joinChannel, [channelId, userId, orgId, token]),
          returnValue:
              Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{})) as _i2
          .Future<Map<dynamic, dynamic>>);
  @override
  _i2.Future<dynamic> getChannelMessages(
          String? channelId, String? orgId, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#getChannelMessages, [channelId, orgId, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> sendChannelMessages(String? channelId, String? userId,
          String? orgId, String? message, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(
              #sendChannelMessages, [channelId, userId, orgId, message, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<List<dynamic>> getRepliesToMessages(
          dynamic channelMessageId, dynamic orgId) =>
      (super.noSuchMethod(
          Invocation.method(#getRepliesToMessages, [channelMessageId, orgId]),
          returnValue:
              Future<List<dynamic>>.value(<dynamic>[])) as _i2
          .Future<List<dynamic>>);
  @override
  _i2.Future<bool> addReplyToMessage(String? channelMessageId, dynamic content,
          dynamic files, dynamic orgId, dynamic userId, dynamic channelId) =>
      (super.noSuchMethod(
          Invocation.method(#addReplyToMessage,
              [channelMessageId, content, files, orgId, userId, channelId]),
          returnValue: Future<bool>.value(false)) as _i2.Future<bool>);
  @override
  _i2.Future<List<_i15.ChannelModel>> fetchChannel(
          String? orgId, dynamic token) =>
      (super.noSuchMethod(Invocation.method(#fetchChannel, [orgId, token]),
              returnValue:
                  Future<List<_i15.ChannelModel>>.value(<_i15.ChannelModel>[]))
          as _i2.Future<List<_i15.ChannelModel>>);
  @override
  _i2.Future<bool> createChannels(
          {String? name,
          String? owner,
          String? email,
          String? orgId,
          String? description,
          bool? private,
          dynamic token}) =>
      (super.noSuchMethod(
          Invocation.method(#createChannels, [], {
            #name: name,
            #owner: owner,
            #email: email,
            #orgId: orgId,
            #description: description,
            #private: private,
            #token: token
          }),
          returnValue: Future<bool>.value(false)) as _i2.Future<bool>);
  @override
  dynamic getChannelPage(String? id, String? orgId, dynamic token) => super
      .noSuchMethod(Invocation.method(#getChannelPage, [id, orgId, token]));
  @override
  dynamic getChannelMembers(String? id, String? orgId, dynamic token) => super
      .noSuchMethod(Invocation.method(#getChannelMembers, [id, orgId, token]));
  @override
  List<_i9.ThemeData> getThemes() =>
      (super.noSuchMethod(Invocation.method(#getThemes, []),
          returnValue: <_i9.ThemeData>[]) as List<_i9.ThemeData>);
  @override
  void sendGetRequest(dynamic endpoint) =>
      super.noSuchMethod(Invocation.method(#sendGetRequest, [endpoint]),
          returnValueForMissingStub: null);
  @override
  _i2.Future<dynamic> sendPostRequest(dynamic body, dynamic endpoint) =>
      (super.noSuchMethod(Invocation.method(#sendPostRequest, [body, endpoint]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> sendPatchRequest(
          dynamic body, dynamic endpoint, dynamic userId) =>
      (super.noSuchMethod(
          Invocation.method(#sendPatchRequest, [body, endpoint, userId]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> allChannelsList(String? currentOrgId, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(#allChannelsList, [currentOrgId, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> joinedChannelsList(
          String? currentOrgId, String? currentUserId, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(
              #joinedChannelsList, [currentOrgId, currentUserId, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i2.Future<dynamic> fetchListOfMembers(
          String? currentOrgId, String? channelId, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(
              #fetchListOfMembers, [currentOrgId, channelId, token]),
          returnValue: Future<dynamic>.value()) as _i2.Future<dynamic>);
  @override
  _i4.Failure handleApiError(_i3.DioError? e) =>
      (super.noSuchMethod(Invocation.method(#handleApiError, [e]),
          returnValue: _FakeFailure_2()) as _i4.Failure);
  @override
  _i2.Future<String> uploadImage(_i21.File? image,
          {String? token, String? memberId, String? orgId}) =>
      (super.noSuchMethod(
          Invocation.method(#uploadImage, [image],
              {#token: token, #memberId: memberId, #orgId: orgId}),
          returnValue: Future<String>.value('')) as _i2.Future<String>);
  @override
  _i2.Future<void> addMemberToChannel(
          String? channelId, String? orgId, String? userId, dynamic token) =>
      (super.noSuchMethod(
          Invocation.method(
              #addMemberToChannel, [channelId, orgId, userId, token]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i2.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i21.ConnectivityService {
  @override
  bool get hasConnection =>
      (super.noSuchMethod(Invocation.getter(#hasConnection), returnValue: false)
          as bool);
  @override
  set hasConnection(bool? _hasConnection) =>
      super.noSuchMethod(Invocation.setter(#hasConnection, _hasConnection),
          returnValueForMissingStub: null);
  @override
  _i22.ConnectivityStatus get networkStatus => (super.noSuchMethod(
      Invocation.getter(#networkStatus),
      returnValue: _i22.ConnectivityStatus.wifi) as _i22.ConnectivityStatus);
  @override
  set networkStatus(_i22.ConnectivityStatus? _networkStatus) =>
      super.noSuchMethod(Invocation.setter(#networkStatus, _networkStatus),
          returnValueForMissingStub: null);
  @override
  _i2.StreamController<dynamic> get connectionChangeController =>
      (super.noSuchMethod(Invocation.getter(#connectionChangeController),
              returnValue: _FakeStreamController_0<dynamic>())
          as _i2.StreamController<dynamic>);
  @override
  set connectionChangeController(
          _i2.StreamController<dynamic>? _connectionChangeController) =>
      super.noSuchMethod(
          Invocation.setter(
              #connectionChangeController, _connectionChangeController),
          returnValueForMissingStub: null);
  @override
  _i2.Stream<dynamic> get connectionChange =>
      (super.noSuchMethod(Invocation.getter(#connectionChange),
          returnValue: Stream<dynamic>.empty()) as _i2.Stream<dynamic>);
  @override
  void initialize() => super.noSuchMethod(Invocation.method(#initialize, []),
      returnValueForMissingStub: null);
  @override
  _i2.Future<bool> checkConnection() =>
      (super.noSuchMethod(Invocation.method(#checkConnection, []),
          returnValue: Future<bool>.value(false)) as _i2.Future<bool>);
  @override
  void onChange() => super.noSuchMethod(Invocation.method(#onChange, []),
      returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [JumpToApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockJumpToApi extends _i1.Mock implements _i23.JumpToApi {
  @override
  String get allChannelsPath =>
      (super.noSuchMethod(Invocation.getter(#allChannelsPath), returnValue: '')
          as String);
  @override
  String get joinedChannelsPath => (super
          .noSuchMethod(Invocation.getter(#joinedChannelsPath), returnValue: '')
      as String);
  @override
  Map<String, dynamic> get headers =>
      (super.noSuchMethod(Invocation.getter(#headers),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  set headers(Map<String, dynamic>? _headers) =>
      super.noSuchMethod(Invocation.setter(#headers, _headers),
          returnValueForMissingStub: null);
  @override
  _i2.Future<List<_i24.ChannelsSearch>> allChannelsList() =>
      (super.noSuchMethod(Invocation.method(#allChannelsList, []),
              returnValue: Future<List<_i24.ChannelsSearch>>.value(
                  <_i24.ChannelsSearch>[]))
          as _i2.Future<List<_i24.ChannelsSearch>>);
  @override
  _i2.Future<List<_i24.ChannelsSearch>> joinedChannelsList() =>
      (super.noSuchMethod(Invocation.method(#joinedChannelsList, []),
              returnValue: Future<List<_i24.ChannelsSearch>>.value(
                  <_i24.ChannelsSearch>[]))
          as _i2.Future<List<_i24.ChannelsSearch>>);
  @override
  _i2.Future<List<_i20.UserSearch>> fetchListOfMembers() => (super.noSuchMethod(
          Invocation.method(#fetchListOfMembers, []),
          returnValue: Future<List<_i20.UserSearch>>.value(<_i20.UserSearch>[]))
      as _i2.Future<List<_i20.UserSearch>>);
  @override
  _i2.Future<List<_i20.NewUser>> fetchList() =>
      (super.noSuchMethod(Invocation.method(#fetchList, []),
              returnValue: Future<List<_i20.NewUser>>.value(<_i20.NewUser>[]))
          as _i2.Future<List<_i20.NewUser>>);
  @override
  String toString() => super.toString();
}
